version: '3'
services:
  dind:
    image: docker:dind
    privileged: true
    command: --host=tcp://0.0.0.0:2375 --tls=false
    volumes:
      - dind-storage:/var/lib/docker

  spawn:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DOCKER_HOST=tcp://dind:2375

volumes:
  dind-storage: