version: '3'
services:
  dind:
    image: docker:dind
    privileged: true
    volumes:
      - dind-storage:/var/lib/docker
      - dind-socket:/var/run/

  spawn:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - dind-socket:/var/run/
    depends_on:
      - dind

volumes:
  dind-storage:
  dind-socket:
